name: Analyze Proxies           # ← اختیاری

on:
  schedule:                     # ← لازم برای اجرا هر ساعت
    - cron: "0 * * * *"         # UTC; رأس هر ساعت
  workflow_dispatch:            # ← اجرای دستی از تب Actions

concurrency:
  group: analyze-proxies
  cancel-in-progress: false

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 58

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run analyzer
        run: |
          python utils/analyze.py

      - name: Commit updated reports
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@users.noreply"
          git add data/output/*.json data/logs/*.json data/tmp/analyze_state.json
          git commit -m "auto: update reports $(date -u '+%Y-%m-%d %H:%M')" || echo "nothing to commit"
          git push
